# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 02:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0002_auto_20170323_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStats',
            new_name='UserStat',
        ),
    ]
