# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 22:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("NLP4CCB", "0004_auto_20170330_0255")]

    operations = [
        migrations.RenameField(
            model_name="userstat", old_name="index", new_name="meronyms_index"
        ),
        migrations.AddField(
            model_name="userstat",
            name="antonyms_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstat",
            name="hyponyms_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstat",
            name="synonyms_index",
            field=models.IntegerField(default=0),
        ),
    ]
