# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-01 01:42


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NLP4CCB', '0005_auto_20170415_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_word', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('hyponyms', 'hyponyms'), ('meronyms', 'meronyms'), ('antonyms', 'antonyms'), ('synonyms', 'synonyms')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
