# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NLP4CCB', '0006_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ind', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_rel', models.CharField(max_length=50)),
                ('avg_score', models.FloatField(default=0.0)),
                ('std_dev', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='userstat',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
