# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0008_auto_20170601_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstat',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
