# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0008_auto_20171102_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcretenessStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=0)),
                ('sem_rel', models.CharField(max_length=50)),
                ('avg_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('rounds_played', models.IntegerField(default=0)),
            ],
        ),
    ]
