# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0009_wordstat_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='last_login',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
