# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0010_userstat_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='times_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relation',
            name='times_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relation',
            name='times_suggested',
            field=models.IntegerField(default=1),
        ),
    ]
