# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0011_picturesstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesstat',
            name='link',
            field=models.CharField(default='www.know-your-nyms.com', max_length=2000),
        ),
    ]
