# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0013_auto_20180114_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretenessstat',
            name='unknown_entered',
            field=models.IntegerField(default=0),
        ),
    ]
