# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NLP4CCB', '0014_concretenessstat_unknown_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPictureInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('word_score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
