# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-02 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP4CCB', '0015_userpictureinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturesstat',
            name='link',
            field=models.TextField(),
        ),
    ]
